"""empty message

Revision ID: 542793fd6d68
Revises: 5e0d6a65bf1b
Create Date: 2021-02-16 23:31:03.229966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '542793fd6d68'
down_revision = '5e0d6a65bf1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
