"""changed id to uuid in User

Revision ID: 5e0d6a65bf1b
Revises: a540dd806afa
Create Date: 2021-02-16 21:39:57.705915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e0d6a65bf1b'
down_revision = 'a540dd806afa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    # ### end Alembic commands ###
